name: fetch-merge-update
on:
  push:
    branches:
      - main
    paths:
      - tools/run.sh
      - .github/workflows/**
  schedule:
    - cron: 10 5 * * *
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./tools/run.sh
      - name: Commit files
        run: |
          git config --local user.email "2857309+hroost@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -u
          git diff-index --quiet HEAD || git commit -a -m "[auto] data update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
